package com.lamp.entities;

public enum ApplicationStatus {
	APPLIED, QUESTIONNAIRE,TEST, AWAITING_INTERVIEW, SCHEDULED_FOR_INTERVIEW, INTERVIEWING, INTERVIEWED, OFFERED_ADMISSION, ACCEPTED, REJECTED, ENROLLED,NATIVE 

}
